Логирование



2025-03-25 20:38:34.284910
<built-in method now of type object at 0x00007FFBE25D7B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Поиск Крым.lnk

2025-03-25 20:38:36.050793
2025-03-25 20:38:36.050793: Программа была успешно установлена на ПК!

2025-03-27 06:56:43.881691
<built-in method now of type object at 0x00007FFC08D17B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Liza Alert.lnk

2025-03-27 06:56:45.430323
2025-03-27 06:56:45.430323: Программа была успешно установлена на ПК!

2025-03-27 06:57:16.881187
<built-in method now of type object at 0x00007FFC08D17B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Liza Alert.lnk

2025-03-27 06:57:18.704055
2025-03-27 06:57:18.704055: Программа была успешно установлена на ПК!

2025-03-27 08:06:33.459681
<built-in method now of type object at 0x00007FF8E6277B60>: Создан ярлык программы по пути: C:\Users\Vanechka\Desktop\Liza Alert.lnk

2025-03-27 08:06:36.131743
2025-03-27 08:06:36.131743: Программа была успешно установлена на ПК!

2025-03-27 08:10:08.372227
ФИО: Фамилия Имя Отчество
Возраст: 18 лет
Город: Евпатория
Описание: Описание написано тут
Приметы: Приметы тут
Одежда: Одежда тут
Фото на ПК: C:/Users/Vanechka/Pictures/Молли.png

2025-03-27 08:18:14.503505
ФИО: Фамилия Имя Отчество
Возраст: 18 лет
Город: Евпатория
Описание: Описание написано тут
Приметы: Приметы тут
Одежда: Одежда тут
Фото на ПК: C:/Users/Vanechka/Pictures/Молли.png

2025-03-27 08:20:55.420081
ФИО: Фамилия Имя Отчество
Возраст: 18 лет
Город: Евпатория
Описание: Описание написано тут
Приметы: Приметы тут
Одежда: Одежда тут
Фото на ПК: C:/Users/Vanechka/Pictures/Молли.png

2025-03-27 08:28:44.857374
<built-in method now of type object at 0x00007FF8E79E7B60>: Создан ярлык программы по пути: C:\Users\Vanechka\Desktop\Liza Alert.lnk

2025-03-27 08:28:46.826432
2025-03-27 08:28:46.826432: Программа была успешно установлена на ПК!

2025-03-27 08:37:31.553947
ФИО: Иванов Иван иванович
Возраст: 48 лет
Город: Иваново
Описание: Высокого роста, худощавый
Приметы: борода
Одежда: Серый пиджак, темные брюки, белые кроссовки
Фото на ПК: C:/Users/Vanechka/Documents/11/photo_2021-06-14_14-33-09.jpg

2025-03-27 08:53:06.789882
Во время проверки исполнения кода произошла ошибка
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1428, in getresponse
  File "http\client.py", line 331, in begin
  File "http\client.py", line 300, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 507, in getresponse
  File "http\client.py", line 1428, in getresponse
  File "http\client.py", line 331, in begin
  File "http\client.py", line 300, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_code.py", line 15, in checker
  File "logs.py", line 89, in get_file_by_name
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))


2025-03-27 08:54:59.302603
Во время проверки исполнения кода произошла ошибка
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1042, in _create
  File "ssl.py", line 1320, in do_handshake
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
  File "urllib3\connectionpool.py", line 468, in _make_request
  File "urllib3\connectionpool.py", line 369, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_code.py", line 15, in checker
  File "logs.py", line 89, in get_file_by_name
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 713, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=None)


2025-03-28 07:54:31.551321
<built-in method now of type object at 0x00007FF8E5407B60>: Создан ярлык программы по пути: C:\Users\Vanechka\Desktop\Liza Alert.lnk

2025-03-28 07:54:33.992404
2025-03-28 07:54:33.992404: Программа была успешно установлена на ПК!

2025-03-28 08:24:26.832053
Во время проверки исполнения кода произошла ошибка
Traceback (most recent call last):
  File "urllib3\connection.py", line 199, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 693, in connect
  File "urllib3\connection.py", line 208, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001F89BCDDEE0>, 'Connection to api.github.com timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Redy3824723/Liza-Alert/contents?ref=main (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F89BCDDEE0>, 'Connection to api.github.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_code.py", line 15, in checker
  File "logs.py", line 89, in get_file_by_name
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 688, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Redy3824723/Liza-Alert/contents?ref=main (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F89BCDDEE0>, 'Connection to api.github.com timed out. (connect timeout=None)'))


2025-03-28 14:32:55.435447
<built-in method now of type object at 0x00007FFC09077B60>: Создан ярлык программы по пути: C:\Users\User\Desktop\Liza Alert.lnk

2025-03-28 14:32:57.017330
2025-03-28 14:32:57.017330: Программа была успешно установлена на ПК!

2025-03-28 14:36:36.793120
ФИО: Иванов
Возраст: 26 лет
Город: Ялта
Описание: глаза карие, волсы седые, глаза впалые
Приметы: шрам на правой брови
Одежда: Красная ветровка, черные джинсы, черные кеды
Фото на ПК: C:/Users/User/Downloads/scale_1200.png

2025-03-28 18:36:14.558494
ФИО: Иванов Петр Сергеевич
Возраст: 27 лет
Город: Ялта
Описание: с 1 января его местонахождение неизвестно
Приметы: рост 176, глаза карие, волосы русые, над правой бровью шрам
Одежда: красная толстовка, черные брюки, черный кроссовки. С собой красный рюкзак
Фото на ПК: C:/Users/User/Downloads/scale_1200.png

2025-03-29 07:43:29.148613
<built-in method now of type object at 0x00007FF8E5CC7B60>: Создан ярлык программы по пути: C:\Users\Vanechka\Desktop\Liza Alert.lnk

2025-03-29 07:43:31.512467
2025-03-29 07:43:31.512467: Программа была успешно установлена на ПК!

2025-04-01 14:05:20.097147
ФИО:  Ф И О
Возраст: 65 лет
Город: Евпа
Описание: Описание
Приметы: Нет
Одежда: Нет
Фото на ПК: C:/Users/Redy/Pictures/image.png

2025-04-01 14:06:56.631369
ФИО: ПР ЕРК РЕК
Возраст: 54 лет
Город: ПРУ
Описание: ркер
Приметы:  ркер
Одежда:  ркркрк
Фото на ПК: C:/Users/Redy/Pictures/image.png

2025-04-01 14:15:54.844198
ФИО: HE ERG ER
Возраст: 43 лет
Город: РУ ру
Описание:  ркерке
Приметы: ркерк
Одежда: ркеек
Фото на ПК: C:/Users/Redy/Pictures/image.png

2025-04-01 14:27:12.327474
<built-in method now of type object at 0x00007FFC16CD7B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Liza Alert.lnk

2025-04-01 14:27:14.135495
2025-04-01 14:27:14.135495: Программа была успешно установлена на ПК!

2025-04-02 10:49:51.634181
<built-in method now of type object at 0x00007FFBDC797B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Поиск Крым.lnk

2025-04-02 10:49:53.261584
2025-04-02 10:49:53.261584: Программа была успешно установлена на ПК!

2025-04-02 13:08:02.959544
<built-in method now of type object at 0x00007FFBDED17B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Поиск Крым.lnk

2025-04-02 13:08:05.036737
2025-04-02 13:08:05.036737: Программа была успешно установлена на ПК!

2025-04-02 13:18:16.097641
<built-in method now of type object at 0x00007FFBDBD77B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Поиск Крым.lnk

2025-04-02 13:18:17.736905
2025-04-02 13:18:17.736905: Программа была успешно установлена на ПК!

2025-04-04 16:03:41.014624
<built-in method now of type object at 0x00007FFC160D7B60>: Создан ярлык программы по пути: C:\Users\Redy\Desktop\Поиск Крым.lnk

2025-04-04 16:03:42.960487
2025-04-04 16:03:42.960487: Программа была успешно установлена на ПК!

2025-04-04 16:05:30.862350
ФИО: Иванов Иван Иванович
Возраст: 50 лет
Город: Евпатория
Описание: Красивый
Приметы: Худощавый
Одежда: Современная
Фото на ПК: C:/Users/Redy/Downloads/f07854edb41badd0a0f0fc5dd75d3a0e.jpg

2025-04-05 12:08:54.205857
<built-in method now of type object at 0x00007FFBDC427B60>: Создан ярлык программы по пути: C:\Users\User\Desktop\Поиск Крым.lnk

2025-04-05 12:08:55.712971
2025-04-05 12:08:55.712971: Программа была успешно установлена на ПК!

2025-04-05 12:11:11.291722
ФИО: Сидоров Сергей Петрович
Возраст: 27 лет
Город: Керчь
Описание: 1 апреля 2025 года его местонахождение неизвестно
Приметы: худощавого телосложения, глаза карие, волосы темные
Одежда: Черная куртка, голубые джинсы, черные кроссовки. С собой синий рюкзак
Фото на ПК: C:/Users/User/Downloads/scale_1200.png

2025-04-05 12:12:40.059150
<built-in method now of type object at 0x00007FFBC74A7B60>: Создан ярлык программы по пути: C:\Users\User\Desktop\Поиск Крым.lnk

2025-04-05 12:12:41.555327
2025-04-05 12:12:41.555327: Программа была успешно установлена на ПК!

2025-04-05 15:05:21.320410
<built-in method now of type object at 0x00007FFECA887B60>: Создан ярлык программы по пути: C:\Users\Книга\Desktop\Поиск Крым.lnk

2025-04-05 15:05:34.719351
2025-04-05 15:05:34.719351: Программа была успешно установлена на ПК!

2025-04-05 15:10:23.141591
ФИО: Ризаов Раровр Пово
Возраст: 34 лет
Город: Рриыо
Описание: осмио воиовы виовиоо ауоу
Приметы: оаиаиу
Одежда: руур
Фото на ПК: C:/Users/Книга/Documents/photo_2024-07-24_00-25-37.jpg

2025-04-05 15:33:45.294745
Во время проверки исполнения кода произошла ошибка
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1042, in _create
  File "ssl.py", line 1320, in do_handshake
ConnectionAbortedError: [WinError 10053] Программа на вашем хост-компьютере разорвала установленное подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 455, in wrap_socket
  File "ssl.py", line 1042, in _create
  File "ssl.py", line 1320, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, 'Программа на вашем хост-компьютере разорвала установленное подключение', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_code.py", line 15, in checker
  File "logs.py", line 96, in get_file_by_name
  File "logs.py", line 119, in read_file_content
  File "logs.py", line 26, in get_file_sha
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'Программа на вашем хост-компьютере разорвала установленное подключение', None, 10053, None))


2025-04-05 16:00:21.318334
<built-in method now of type object at 0x00007FFC15A07B60>: Создан ярлык программы по пути: C:\Users\User\Desktop\Поиск Крым.lnk

2025-04-05 16:00:22.811617
2025-04-05 16:00:22.811617: Программа была успешно установлена на ПК!

2025-04-05 16:03:52.540673
<built-in method now of type object at 0x00007FFC15A87B60>: Создан ярлык программы по пути: C:\Users\User\Desktop\Поиск Крым.lnk

2025-04-05 16:03:54.112358
2025-04-05 16:03:54.112358: Программа была успешно установлена на ПК!

2025-04-05 16:05:09.548037
ФИО: Иванов Иван Иванович
Возраст: 47 лет
Город: Ялта
Описание: с 1 января его местонахождение неизвестно
Приметы: ходит с палочкой
Одежда: красная куртка красные штаны, черные кеды
Фото на ПК: C:/Users/User/Downloads/vCZKLmdeauU.jpg

2025-04-05 16:13:52.538680
<built-in method now of type object at 0x00007FFAEBC57B60>: Создан ярлык программы по пути: C:\Users\User\Desktop\Поиск Крым.lnk

2025-04-05 16:13:54.062244
2025-04-05 16:13:54.062244: Программа была успешно установлена на ПК!

2025-04-05 16:14:00.932204
<built-in method now of type object at 0x00007FFBF8727B60>: Создан ярлык программы по пути: C:\Users\Book\Desktop\Поиск Крым.lnk

2025-04-05 16:14:02.703204
2025-04-05 16:14:02.703204: Программа была успешно установлена на ПК!

2025-04-05 16:17:26.098160
ФИО: Петров (Федоров, Кзьмин) Петр Петрович
Возраст: 80 лет
Город: Симферополь
Описание: 03.04.2025 ушел  из дома
Приметы: рост 160 см, нормального телосложения, волосы седые, глаза карие. 
Одежда: серая куртка, белый свитер, черные спортивные штаны, черные сапоги, красная шапка
Фото на ПК: C:/Users/Book/Desktop/2773149451.jpg

2025-04-05 16:17:31.535911
ФИО: Иванов Иван Иванович
Возраст: 41 лет
Город: Ялта
Описание: 5 марта вышел из дома и не вернулся
Приметы: Худощавого телосложения, волосы русые, глаза карие, ходит с палочкой
Одежда: Синяя рубашка, черные брюки, синяя жилетка. С собой черный роюкзак
Фото на ПК: C:/Users/User/Downloads/scale_1200.png

2025-04-05 16:20:23.598510
ФИО: Константинов Константин Кнстантинович
Возраст: 80 лет
Город: Симферополь
Описание: 03.04.2025 ушел  из дома
Приметы: рост 160 см, нормального телосложения, волосы седые, глаза карие. 
Одежда: серая куртка, белый свитер, черные спортивные штаны, черные сапоги, красная шапка
Фото на ПК: C:/Users/Book/Desktop/2773149451.jpg

2025-04-06 16:35:52.678569
ФИО: Супренко Даниил
Возраст: 2014 лет
Город: с.Урожайное, Симферопольский район
Описание: 6апреля ушёл из дома.
Приметы: рост 135 см, худощавого телосложения, волосы русые, глаза карие.
Одежда: синяя куртка, ёрные спортивные штаны, чёрные сапоги,зелёная шапка.
Фото на ПК: E:/rMrbh_sPHgQ (1).jpg

2025-04-06 17:11:12.552138
<built-in method now of type object at 0x00007FFAEB9A7B60>: Создан ярлык программы по пути: C:\Users\User\Desktop\Поиск Крым.lnk